# Generated by Django 5.2.17 on 2026-08-08 16:46

import clients.models
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_year', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^\\d{4}$', "Tug'ilgan yil 4 ta raqamdan iborat bo'lishi kerak"), clients.models.validate_birth_year_range])),
                ('address', models.CharField(max_length=500)),
                ('workplace', models.CharField(max_length=200)),
                ('service_type', models.CharField(default='Ichak infeksiyasi', max_length=255)),
                ('status', models.CharField(choices=[('yangi', 'Yangi'), ("ko'rildi", "Ko'rildi"), ('tugatildi', 'Tugatildi')], default='yangi', max_length=20)),
                ('payment_status', models.CharField(choices=[('kutilmoqda', 'Kutilmoqda'), ('tolangan', "To'langan"), ('rad_etilgan', 'Rad etilgan')], default='kutilmoqda', max_length=20)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-registered_at'],
            },
        ),
    ]
